<?php

namespace Database\Factories;

use App\Models\Office;
use Illuminate\Database\Eloquent\Factories\Factory;

class OfficeFactory extends Factory
{
    protected $model = Office::class;

    public function definition(): array
    {
        return [
            'name' => $this->faker->unique()->jobTitle(),
            'slug' => null, // auto-generated by model boot
            'level' => $this->faker->randomElement(['federal', 'state', 'lga']),
            'type' => $this->faker->randomElement(['executive', 'legislative']),
            'description' => $this->faker->sentence(),
            'sort_order' => $this->faker->numberBetween(1, 100),
            'is_active' => true,
            'constituency_id' => null,
        ];
    }
}
